jdk: oraclejdk8
language: android

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
 - chmod +x gradlew
 
android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository-29
    - extra-google-google_play_services-29
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

script: travis/script.sh
after_success: travis/after_success_script.sh