package de.greenrobot.daoexample;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.IdentityScopeType;

import de.greenrobot.daoexample.Locatii;

import de.greenrobot.daoexample.LocatiiDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig locatiiDaoConfig;

    private final LocatiiDao locatiiDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        locatiiDaoConfig = daoConfigMap.get(LocatiiDao.class).clone();
        locatiiDaoConfig.initIdentityScope(type);

        locatiiDao = new LocatiiDao(locatiiDaoConfig, this);

        registerDao(Locatii.class, locatiiDao);
    }
    
    public void clear() {
        locatiiDaoConfig.getIdentityScope().clear();
    }

    public LocatiiDao getLocatiiDao() {
        return locatiiDao;
    }

}
