package de.greenrobot.daoexample;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LOCATII.
 */
public class Locatii {

    private Long id;
    /** Not-null value. */
    private String oras;
    private String adresa;
    private String latitudine;
    private String longitudine;
    private String detaliiAdresa;
    private String persoanaContact1;
    private String nrTelefonPersoanaContact1;
    private String persoanaContact2;
    private String nrTelefonPersoanaContact2;
    private String orar;

    public Locatii() {
    }

    public Locatii(Long id) {
        this.id = id;
    }

    public Locatii(Long id, String oras, String adresa, String latitudine, String longitudine, String detaliiAdresa, String persoanaContact1, String nrTelefonPersoanaContact1, String persoanaContact2, String nrTelefonPersoanaContact2, String orar) {
        this.id = id;
        this.oras = oras;
        this.adresa = adresa;
        this.latitudine = latitudine;
        this.longitudine = longitudine;
        this.detaliiAdresa = detaliiAdresa;
        this.persoanaContact1 = persoanaContact1;
        this.nrTelefonPersoanaContact1 = nrTelefonPersoanaContact1;
        this.persoanaContact2 = persoanaContact2;
        this.nrTelefonPersoanaContact2 = nrTelefonPersoanaContact2;
        this.orar = orar;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getOras() {
        return oras;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOras(String oras) {
        this.oras = oras;
    }

    public String getAdresa() {
        return adresa;
    }

    public void setAdresa(String adresa) {
        this.adresa = adresa;
    }

    public String getLatitudine() {
        return latitudine;
    }

    public void setLatitudine(String latitudine) {
        this.latitudine = latitudine;
    }

    public String getLongitudine() {
        return longitudine;
    }

    public void setLongitudine(String longitudine) {
        this.longitudine = longitudine;
    }

    public String getDetaliiAdresa() {
        return detaliiAdresa;
    }

    public void setDetaliiAdresa(String detaliiAdresa) {
        this.detaliiAdresa = detaliiAdresa;
    }

    public String getPersoanaContact1() {
        return persoanaContact1;
    }

    public void setPersoanaContact1(String persoanaContact1) {
        this.persoanaContact1 = persoanaContact1;
    }

    public String getNrTelefonPersoanaContact1() {
        return nrTelefonPersoanaContact1;
    }

    public void setNrTelefonPersoanaContact1(String nrTelefonPersoanaContact1) {
        this.nrTelefonPersoanaContact1 = nrTelefonPersoanaContact1;
    }

    public String getPersoanaContact2() {
        return persoanaContact2;
    }

    public void setPersoanaContact2(String persoanaContact2) {
        this.persoanaContact2 = persoanaContact2;
    }

    public String getNrTelefonPersoanaContact2() {
        return nrTelefonPersoanaContact2;
    }

    public void setNrTelefonPersoanaContact2(String nrTelefonPersoanaContact2) {
        this.nrTelefonPersoanaContact2 = nrTelefonPersoanaContact2;
    }

    public String getOrar() {
        return orar;
    }

    public void setOrar(String orar) {
        this.orar = orar;
    }

}
